package org.springproject.passwordsummerkeepersimple.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "user_passwords")
public class PasswordInfo {

    @Id
    @Column(name = "password_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int passwordId; // Primary key column, auto-generated by the database

    @Column(name = "password_owner")
    private String passwordOwner; // Column to store the password owner (username of the logged-in user)

    @Column(name = "name")
    private String name; // Column to store the name of the stored account (i.e. Facebook, Instagram, YouTube, etc.)

    @Column(name = "username")
    private String username; // Column to store the username associated with the password

    @Column(name = "password")
    private String password; // Column to store the password

//    @Column(name = "salt_base64")
//    private String saltBase64; // Column to store the salt in Base64 format

    public PasswordInfo(String name, String username, String password) {
        this.name = name;
        this.username = username;
        this.password = password;
    }

    public PasswordInfo() {

    }

    public String getPasswordOwner() {
        return passwordOwner;
    }

    public void setPasswordOwner(String passwordOwner) {
        this.passwordOwner = passwordOwner;
    }

    public int getPasswordId() {
        return passwordId;
    }

    public void setPasswordId(int passwordId) {
        this.passwordId = passwordId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}