package org.springproject.passwordsummerkeepersimple.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "user_accounts") // Specifies the table name for this entity
public class UserAccount {
    @Id
    @Column(name = "user_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int userId; // Primary key column, auto-generated by the database

    @Column(name = "username")
    private String username; // Column to store the username

    @Column(name = "password")
    private String password; // Column to store the password

    @Column(name = "salt_base64")
    private String saltBase64; // Column to store the salt in Base64 format
    @Column(name = "user_role")
    private String roles;

    // Default constructor (required by JPA)
    public UserAccount(){

    }

    public String getRoles() {
        return roles;
    }

    // Constructor with parameters for username and password
    public UserAccount(String username, String password) {
        this.username = username;
        this.password = password;
    }

    // Getter for username
    public String getUsername() {
        return username;
    }

    // Setter for username
    public void setUsername(String username) {
        this.username = username;
    }

    // Getter for password
    public String getPassword() {
        return password;
    }

    // Setter for password
    public void setPassword(String password) {
        this.password = password;
    }

    // Getter for saltBase64
    public String getSaltBase64() {
        return saltBase64;
    }

    // Setter for saltBase64
    public void setSaltBase64(String saltBase64) {
        this.saltBase64 = saltBase64;
    }
}