package org.springproject.passwordsummerkeepersimple.entity;

import jakarta.persistence.*;

import javax.crypto.SecretKey;

@Entity
@Table(name = "user_account_keys") // Specifies the table name for this entity
public class UserAccountKeys {

    @Id
    @Column(name = "key_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int keyId; // Primary key column, auto-generated by the database

    @Column(name = "username")
    private String username; // Column to store the username

    @Column(name = "secret_key")
    private SecretKey secretKey; // Column to store the secret key (using javax.crypto.SecretKey)

    // Default constructor (required by JPA)
    public UserAccountKeys() {
    }

    // Constructor with parameters for username and secretKey
    public UserAccountKeys(String username, SecretKey secretKey) {
        this.username = username;
        this.secretKey = secretKey;
    }

    // Getter for keyId
    public int getKeyId() {
        return keyId;
    }

    // Setter for keyId
    public void setKeyId(int keyId) {
        this.keyId = keyId;
    }

    // Getter for username
    public String getUsername() {
        return username;
    }

    // Setter for username
    public void setUsername(String username) {
        this.username = username;
    }

    // Getter for secretKey
    public SecretKey getSecretKey() {
        return secretKey;
    }

    // Setter for secretKey
    public void setSecretKey(SecretKey secretKey) {
        this.secretKey = secretKey;
    }
}